version: '3.8'

services:
  # -----------------------------------
  # 1. EL LADO DE LA BASE DE DATOS
  # -----------------------------------
  postgres-db:
    image: postgres:15-alpine
    container_name: nexoohub_postgres
    restart: always
    environment:
      POSTGRES_DB: nexoohub_almacen
      POSTGRES_USER: nexoohub_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-MiClaveSecreta999}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - red-interna
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexoohub_user -d nexoohub_almacen"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # -----------------------------------
  # 2. EL LADO DE JAVA (SPRING BOOT)
  # -----------------------------------
  java-backend:
    build: .
    container_name: nexoohub_java_app
    restart: always
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:postgresql://postgres-db:5432/nexoohub_almacen
      - DB_USER=nexoohub_user
      - DB_PASSWORD=${DB_PASSWORD:-MiClaveSecreta999}
      - JWT_SECRET=${JWT_SECRET:-NexooHubSuperSecretKeyParaFirmaDeTokens2026!}
      - MAIL_USERNAME=${MAIL_USERNAME:-nexoohub.erp@gmail.com}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-}
      - MAIL_FROM=${MAIL_FROM:-nexoohub.erp@gmail.com}
      - TELEGRAM_ENABLED=${TELEGRAM_ENABLED:-false}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
    ports:
      - "8080:8080"
    networks:
      - red-interna

# Definición del volumen para la persistencia
volumes:
  pgdata:

# Definición de la red para que los contenedores se hablen entre sí
networks:
  red-interna:
    driver: bridge