openapi: 3.0.0
info:
  title: API de Autenticación
  description: API para la autenticación de usuarios y generación de tokens JWT.
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  /auth/login:
    post:
      summary: Autenticar usuario y obtener token
      description: Proporciona un nombre de usuario y contraseña para recibir un token JWT de autenticación.
      operationId: login
      tags:
        - Seguridad
      requestBody:
        description: Credenciales del usuario.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Autenticación exitosa.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseAuthResponse'
        '401':
          description: Credenciales inválidas.

components:
  schemas:
    LoginRequest:
      type: object
      properties:
        username:
          type: string
          description: Nombre de usuario.
        password:
          type: string
          description: Contraseña del usuario.
      required:
        - username
        - password

    AuthResponse:
      type: object
      properties:
        token:
          type: string
          description: Token JWT.

    ApiResponseAuthResponse:
      type: object
      properties:
        mensaje:
          type: string
          example: Autenticación exitosa
        data:
          $ref: '#/components/schemas/AuthResponse'
