openapi: 3.0.0
info:
  title: API de Motos
  description: API para la gestión de motos.
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  /motos:
    get:
      summary: Listar todas las motos
      description: Devuelve una lista de todas las motos.
      operationId: listarMotos
      tags:
        - Catálogo
      responses:
        '200':
          description: Lista de motos obtenida con éxito.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Moto'

    post:
      summary: Registrar una nueva moto
      description: Registra una nueva moto en el sistema.
      operationId: crearMoto
      tags:
        - Catálogo
      requestBody:
        description: Datos de la moto a crear.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MotoInput'
      responses:
        '201':
          description: Moto registrada correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  exitoso:
                    type: boolean
                    example: true
                  mensaje:
                    type: string
                    example: Moto registrada correctamente
                  id:
                    type: integer

  /motos/{id}:
    put:
      summary: Actualizar una moto
      description: Actualiza los datos de una moto existente.
      operationId: actualizarMoto
      tags:
        - Catálogo
      parameters:
        - name: id
          in: path
          description: ID de la moto a actualizar.
          required: true
          schema:
            type: integer
      requestBody:
        description: Datos de la moto a actualizar.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MotoInput'
      responses:
        '200':
          description: Moto actualizada correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  exitoso:
                    type: boolean
                    example: true
                  mensaje:
                    type: string
                    example: Moto actualizada correctamente
        '404':
          description: La moto no fue encontrada.

components:
  schemas:
    Moto:
      type: object
      properties:
        id:
          type: integer
        marca:
          type: string
        modelo:
          type: string
        cilindrada:
          type: string

    MotoInput:
      type: object
      properties:
        marca:
          type: string
        modelo:
          type: string
        cilindrada:
          type: string
      required:
        - marca
        - modelo
